# add_newline = false

[character]
error_symbol='[✖](bold red)'

[ocaml]
format='[$version]($style) '

[python]
format='[$version]($style) '

[memory_usage]
disabled=false
format="[${ram_pct}/${swap_pct}]($style) "
# threshold=-1
